version: "3"

services:
  demo:
    image: hoopoed/appdev_hack_challenge:latest
    volumes:
      - /home/sd924/IthacaTraveller.db:/usr/app/instance/IthacaTraveller.db
    ports:
      - "80:8000"
    env_file:
      - .env
